### ISSUE TITLE
Reference the annotation made in the tracking table and export

### ISSUE THREAD

**Issue by ebbertd** [c3l-lab/OVAL#11]
OVAL lets users create annotations. These annotations are stored in the database in the `annotations` table. That an annotation has been written is also part of the user tracking stored in the `trackings` table.

Example from the `annotations` table:
![image](https://github.com/c3l-lab/OVAL/assets/20522234/5a752d18-b0eb-45e2-a7e8-67676730ac6f)

Example from the `trackings` table:
![image](https://github.com/c3l-lab/OVAL/assets/20522234/cf5f553a-beb7-48bc-9bee-9254d465c793)

When using this data for research, it is crucial to know which annotation has been made when. For this purpose, a column is to be added to the `trackings` table that references the annotation made by the `id` in the `annotations` table. This information also has to be part of the data export that users can request in the user interface.

**Comment by minhtruongdevvn** [comment]
@ebbertd 

```
/* ref_id column will be added to trackings table */
Schema::table('trackings', function (Blueprint $table) {
    $table->integer('ref_id')->unsigned()->nullable()->after('info');
});
```

Should we consider adding ref_type to indicate the type? I noticed we handle multiple types such as comment, annotation, video-control.

**Comment by minhtruongdevvn** [comment]
two column ref_id (the tracked object id) and ref_type (the type of the tracked object, e.i. comment, annotation) was added into the tracking table

**Comment by ebbertd** [comment]
This is working.
