### ISSUE TITLE
Integrate WebGazer

### ISSUE THREAD

**Issue by ebbertd** [c3l-lab/OVAL#27]
TLDR: Integrate WebGazer. See: https://github.com/brownhci/WebGazer

The goal is to enable eye tracking while the learners are watching a video in OVAL. An instructor should be able to enable eye tracking on a per video basis. If eye tracking is enabled for a video and a user opens this video, they will first be asked for their consent to have eye tracking enabled. They can decline and then watch the video as always. If they agree to eye tracking, they first have to calibrate the eye tracking. Once the eye tracking is calibrated, they can watch the video.

**Comment by minhtruongdevvn** [comment]
## _Added table session_information to store information for each video:_
| Field | Description | 
|----------|----------|
| id    |  String: The video session ID     | 
| os    |  String: The operating system of user     | 
| doc_width    | Integer: The width of the whole document (including scroll)     | 
| doc_height    | Integer: The height of the whole document (including scroll)     | 
| init_screen_width    | Integer: The width of the browser window     | 
| init_screen_height    | Integer: The height of the browser window     | 
| layout    | String: Flag represent layout or UI sections (V=>video, A=>annotation,C=>comment)(e.g. VAC means the layout contains both video, annotation, and comment sections)     | 

If user first enter the group video details page, the video will get a new session_id
If user change video but still in browser tab, the video will get a new session_id
If user reload the page but still in browser tab, the video will keep the existing session_id

## _Added session_id column in tracking table:_
The _session_id_ column is associated with the _id_ column in session_information table

## _Added screen resize tracking:_
![image](https://github.com/c3l-lab/OVAL/assets/119903396/66da595d-4a1a-4536-a287-e34268bad062)

## _Eye tracking:_
| Field | Description | 
|----------|----------|
| x    |  Float: The x coordinate predict, where the eye is looking at     | 
| y    |  Float: The y coordinate predict, where the eye is looking at     | 
| id    | String, tag: The width of the whole document (including scroll)     | 
| target    | String, tag: The component predict, where the eye is looking at (V,A,C,O)(O  is for other)     | 
| timestamp    |  Integer: The UNIX time where this is recorded    |

- Eye tracking every 0.5 seconds
- Every week, users will be prompted to provide consent for camera access, tracking, and cookie usage. They have the option to either agree or disagree with each consent request. If a user agrees to the consents, they will be directed to a calibration page where the app collects their gazing patterns
